server:
  port: ${PORT:8080}

security:
  basic:
    enabled: false

zuul:
  routes:
    user:
      path: /user/**
      serviceId: USER-SERVICE
 # add-proxy-headers: true

---
spring:
  profiles: docker

