server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

logging:
  level: debug

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
cassandra:
  contactpoints: 192.168.187.7
  port: 9042
  keyspace: teste

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.187.7:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

---
spring:
  profiles: docker

logging:
  level: warn
  logstash:
    host: logstash

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
