server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

logging:
  level: debug

#Spring boot endpoints
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#Spring boot endpoints
management:
  security:
    enabled: false
    
cassandra:
#  contactpoints: 18.231.28.228,52.67.89.146,54.233.177.125
  contactpoints: 10.128.0.2
  port: 9042
  keyspace: teste
 # loadBalacingDc: AWS_VPC_SA_EAST_1
  auth:
    user: cassandra
    password: amcom2017.

metrics:
  graphite:
    enabled: true
    host: 10.128.0.3
    port: 2003



eureka:
  client:
    serviceUrl:
      defaultZone: http://10.128.0.4:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          
spring:
  http:
    multipart:
      maxFileSize: 128MB
      maxRequestSize: 128MB
---
spring:
  profiles: docker

logging:
  level: warn
  logstash:
    host: logstash

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
