server:
  port: ${PORT:8082}
  
security:
  basic:
    enabled: false
    
rate: 75
process:
  minTime: 100
  maxTime: 200
queue:
  maxSize: 20
  maxThread: 10
  persistPath: /home/sergio/teste/receiver

---

spring:
  profiles: docker
