server:
  port: ${PORT:8082}
  
security:
  basic:
    enabled: false
    
rate: 75
process:
  minTime: 100
  maxTime: 200
queue:
  maxSize: 100
  maxThread: 8
  persistPath: /home/sergio/teste/receiver

---

spring:
  profiles: docker
