server:
  port: ${PORT:8089}
  
security:
  basic:
    enabled: false

queue:
  maxSize: 20
  maxThread: 10
  persistPath: /tmp
ocr:
  maxRetry: 4
  imageResamplePath: /home/sr_gorniski/2mb.png
  persistPath: /tmp
smi:
  numberOfPhotos: 4
  photoSizeInKB: 2000
    
---

spring:
  profiles: docker
