server:
  port: ${PORT:8089}
  
security:
  basic:
    enabled: false

queue:
  maxSize: 20
  maxTread: 10
  persistPath: /home/sergio/teste/receiver
ocr:
  maxRetry: 4
    
---

spring:
  profiles: docker
