server:
  port: ${PORT:8089}
  
security:
  basic:
    enabled: false

queue:
  maxSize: 20
  maxThread: 10
  persistPath: /home/sergio/teste/receiver
ocr:
  maxRetry: 4
  imageResamplePath: /home/sergio/teste/receiver/2mb.png
smi:
  numberOfPhotos: 4
  photoSizeInKB: 2000
    
---

spring:
  profiles: docker
