server:
  port: ${PORT:8083}
  
security:
  basic:
    enabled: false
    
cassandra:
  contactpoints: 192.168.187.111
  port: 9042
  keyspace: teste
  
spark:
  host: 192.168.187.111
  port: 7077
    
---

spring:
profiles: docker
